AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'test/**/*'
    - '*.gemspec'
  DisplayCopNames: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/LineLength:
  Max: 120
Security/Eval:
  Enabled: false
